kind: pipeline
name: default

steps:

- name: dockerhub
  image: plugins/docker
  privileged: true
  settings:
    repo: kexpress/drone-envtpl
    dockerfile: Dockerfile
    purge: false
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag